name: "AWS CloudFormation Delete"

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR  

jobs:
  delete:
    name: "delete"
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/cf-cicd-delete.yaml@main
    secrets: 
      aws-region:  ${{ secrets.AWS_REGION }}
      devl-aws-role-arn: ${{ secrets.DEVL_AWS_ROLE_ARN }}
      devl-kms-key-arn:  ${{ secrets.DEVL_AWS_KMS_KEY_ARN }}
      devl-code-repository-s3-bucket:  ${{ secrets.DEVL_CODE_REPOSITORY_S3_BUCKET }}
      test-aws-role-arn: ${{ secrets.TEST_AWS_ROLE_ARN }}
      test-kms-key-arn: ${{ secrets.TEST_AWS_KMS_KEY_ARN }}
      test-code-repository-s3-bucket:  ${{ secrets.TEST_CODE_REPOSITORY_S3_BUCKET }}
      prod-aws-role-arn: ${{ secrets.PROD_AWS_ROLE_ARN }}
      prod-kms-key-arn: ${{ secrets.PROD_AWS_KMS_KEY_ARN }}
      prod-code-repository-s3-bucket:  ${{ secrets.PROD_CODE_REPOSITORY_S3_BUCKET }}